#include "Application.h"
#include "ModuleInput.h"
#include "ModuleRender.h"
#include "ModuleCollision.h"
#include "ModulePlayer.h"

ModuleCollision::ModuleCollision()
{
	for (uint i = 0; i < MAX_COLLIDERS; ++i)
		colliders[i] = nullptr;


	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BASIC] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_GREENSHIP] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_POWERUPSHIP] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_SHOT] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_POWER_UP_VULCAN] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_POWER_UP_LASER] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_MISSILE] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_EXTRA_POINTS] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_BOX] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_WALL_UP] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_WALL_DOWN] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_BOMB] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_PLAYER][COLLIDER_ENEMY_BOSS] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_MISSILE_HOMING] = true;
	matrix[COLLIDER_PLAYER][COLLIDER_MISSILE_NUCLEAR] = true;



	matrix[COLLIDER_PLAYER_2][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_BASIC] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_GREENSHIP] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_POWERUPSHIP] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_SHOT] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_POWER_UP_VULCAN] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_POWER_UP_LASER] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_MISSILE] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_EXTRA_POINTS] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_BOX] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_WALL_UP] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_WALL_DOWN] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_BOMB] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_PLAYER_2][COLLIDER_ENEMY_BOSS] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_MISSILE_HOMING] = true;
	matrix[COLLIDER_PLAYER_2][COLLIDER_MISSILE_NUCLEAR] = true;


	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_BOMB] = true;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_BASIC][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_BOMB] = true;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_GREENSHIP][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_BOMB] = true;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_POWERUPSHIP][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_BOMB] = true;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_TURRET][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_BASIC] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_GREENSHIP] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_POWERUPSHIP] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_TURRET] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_BOX] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_DARK_BOX] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_BOMB] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_TANK] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_BIGTANK] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_BIGBOAT] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_WAGON] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_ENEMY_BOSS] = true;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_PLAYER_SHOT][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_BASIC] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_GREENSHIP] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_POWERUPSHIP] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_TURRET] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_BOX] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_DARK_BOX] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_BOMB] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_TANK] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_BIGTANK] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_BIGBOAT] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_WAGON] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_ENEMY_BOSS] = true;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_PLAYER_2_SHOT][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_BOMB] = true;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_SHOT][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_BOX] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_BOMB] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_ENEMY_BOSS] = false;	
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_POWER_UP_VULCAN][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_BOX] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_BOMB] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_POWER_UP_LASER][COLLIDER_MISSILE_NUCLEAR] = false;



	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_BOX] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_BOMB] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_EXTRA_POINTS][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_BOX][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_BOX][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_BOX][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_BOX][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_BOX][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_BOX][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_BOX][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_BOX][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_BOX][COLLIDER_BOX] = false;
	matrix[COLLIDER_BOX][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_BOX][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_BOX][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_BOX][COLLIDER_BOMB] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_BOX][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_BOX][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_BOX][COLLIDER_MISSILE_NUCLEAR] = false;
	

	matrix[COLLIDER_DARK_BOX][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_DARK_BOX][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_BOX] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_BOMB] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_DARK_BOX][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_WALL_UP][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_WALL_UP][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_BOX] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_BOMB] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_WALL_UP][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_WALL_DOWN][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_BOX] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_BOMB] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_WALL_DOWN][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_BOMB][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_BOMB][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_BASIC] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_GREENSHIP] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_POWERUPSHIP] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_TURRET] = true;
	matrix[COLLIDER_BOMB][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_BOMB][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_SHOT] = true;
	matrix[COLLIDER_BOMB][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_BOMB][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_BOMB][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_BOMB][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_BOMB][COLLIDER_BOX] = true;
	matrix[COLLIDER_BOMB][COLLIDER_DARK_BOX] = true;
	matrix[COLLIDER_BOMB][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_BOMB][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_BOMB][COLLIDER_BOMB] = false;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_TANK] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_BIGTANK] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_BIGBOAT] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_WAGON] = true;
	matrix[COLLIDER_BOMB][COLLIDER_ENEMY_BOSS] = true;
	matrix[COLLIDER_BOMB][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_BOMB][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_ENEMY_TANK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_BOMB] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_TANK][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_BOMB] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_BIGTANK][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_BOMB] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_BIGBOAT][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_PLAYER] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_PLAYER_2] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_BOMB] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_WAGON][COLLIDER_MISSILE_NUCLEAR] = false;


	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_PLAYER_SHOT] = true;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_PLAYER_2_SHOT] = true;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_BOX] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_BOMB] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_ENEMY_BOSS][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_PLAYER_SHOT] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_BOX] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_BOMB] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_MISSILE_HOMING][COLLIDER_MISSILE_NUCLEAR] = false;

	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_PLAYER] = true;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_PLAYER_2] = true;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_BASIC] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_GREENSHIP] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_POWERUPSHIP] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_TURRET] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_PLAYER_2_SHOT] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_SHOT] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_POWER_UP_VULCAN] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_POWER_UP_LASER] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_MISSILE] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_EXTRA_POINTS] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_BOX] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_DARK_BOX] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_WALL_UP] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_WALL_DOWN] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_BOMB] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_TANK] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_BIGTANK] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_BIGBOAT] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_WAGON] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_ENEMY_BOSS] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_MISSILE_HOMING] = false;
	matrix[COLLIDER_MISSILE_NUCLEAR][COLLIDER_MISSILE_NUCLEAR] = false;

}


// Destructor
ModuleCollision::~ModuleCollision()
{}


bool ModuleCollision::Start() {
	for (uint i = 0; i < MAX_COLLIDERS; ++i)
		colliders[i] = nullptr;
	return true;
}

update_status ModuleCollision::PreUpdate()
{
	// Remove all colliders scheduled for deletion
	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		if(colliders[i] != nullptr && colliders[i]->to_delete == true)
		{

			delete colliders[i];
			colliders[i] = nullptr;
		}
	}

	return UPDATE_CONTINUE;
}

// Called before render is available
update_status ModuleCollision::Update()
{
	Collider* c1;
	Collider* c2;

	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		// skip empty colliders
		if(colliders[i] == nullptr)
			continue;

		c1 = colliders[i];

		// avoid checking collisions already checked
		for(uint k = i+1; k < MAX_COLLIDERS; ++k)
		{
			// skip empty colliders
			if(colliders[k] == nullptr)
				continue;

			c2 = colliders[k];

			if(c1->CheckCollision(c2->rect) == true)
			{
				if (matrix[c1->type][c2->type] && c1->callback)
					c1->callback->OnCollision(c1, c2);

				if (matrix[c2->type][c1->type] && c2->callback)
					c2->callback->OnCollision(c2, c1);
			}
		}
	}

	DebugDraw();

	return UPDATE_CONTINUE;
}

void ModuleCollision::DebugDraw()
{
	if(App->input->keyboard[SDL_SCANCODE_F2] == KEY_DOWN)
		debug = !debug;

	if(debug == false)
		return;

	Uint8 alpha = 80;
	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		if(colliders[i] == nullptr)
			continue;
		
		switch(colliders[i]->type)
		{
			case COLLIDER_NONE: // white
			App->render->DrawQuad(colliders[i]->rect, 0, 0, 255, alpha);
			break;
			case COLLIDER_WALL_UP: // white
			App->render->DrawQuad(colliders[i]->rect, 255, 255, 255, alpha);
				break;
			case COLLIDER_WALL_DOWN: // white
			App->render->DrawQuad(colliders[i]->rect, 255, 255, 255, alpha);
				break;
			case COLLIDER_PLAYER: // green
			App->render->DrawQuad(colliders[i]->rect, 0, 255, 0, alpha);
			break;
			case COLLIDER_PLAYER_2: // green
			App->render->DrawQuad(colliders[i]->rect, 0, 255, 0, alpha);
			break;
			case COLLIDER_ENEMY_BASIC: // red
			App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
			break;
			case COLLIDER_ENEMY_TANK: // red
			App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
			break;
			case COLLIDER_ENEMY_GREENSHIP: // red
			App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
			break;
			case COLLIDER_ENEMY_POWERUPSHIP: // red
			App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
			break;
			case COLLIDER_ENEMY_BOSS: // red
				App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
				break;
			case COLLIDER_POWER_UP_LASER: // red
			App->render->DrawQuad(colliders[i]->rect, 0, 0, 255, alpha);
			break;
			case COLLIDER_POWER_UP_VULCAN: // red
				App->render->DrawQuad(colliders[i]->rect, 0, 0, 255, alpha);
				break;
			case COLLIDER_ENEMY_TURRET: // red
			App->render->DrawQuad(colliders[i]->rect, 255, 0, 0, alpha);
			break;

			case COLLIDER_PLAYER_SHOT: // yellow
			App->render->DrawQuad(colliders[i]->rect, 0, 0, 255, alpha);
			break;

			case COLLIDER_PLAYER_2_SHOT: // yellow
			App->render->DrawQuad(colliders[i]->rect, 0, 0, 255, alpha);
			break;
			case COLLIDER_ENEMY_SHOT: // magenta
			App->render->DrawQuad(colliders[i]->rect, 0, 255, 255, alpha);
			break;
		}
	}
}

// Called before quitting
bool ModuleCollision::CleanUp()
{
	LOG("Freeing all colliders");

	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		if(colliders[i] != nullptr)
		{
			delete colliders[i];
			colliders[i] = nullptr;
		}
	}

	return true;
}

Collider* ModuleCollision::AddCollider(SDL_Rect rect, COLLIDER_TYPE type, Module* callback)
{
	Collider* ret = nullptr;

	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		if(colliders[i] == nullptr)
		{
			ret = colliders[i] = new Collider(rect, type, callback);
			break;
		}
	}

	return ret;
}

bool ModuleCollision::EraseCollider(Collider* collider)
{
	for(uint i = 0; i < MAX_COLLIDERS; ++i)
	{
		if(colliders[i] == collider)
		{
			delete colliders[i];
			colliders[i] = nullptr;
			return true;
		}
	}

	return false;
}

// -----------------------------------------------------

bool Collider::CheckCollision(const SDL_Rect& r) const
{
	bool collision = false;


		if (rect.x +rect.w >= r.x && rect.x <= r.x + r.w) {
			if (rect.y + rect.h >= r.y && rect.y <= r.y + r.h) {

				collision = true;
			}
		}

	return  collision;
}